### ISSUE TITLE
Unable to Join Cluster

### ISSUE THREAD

**Issue by psybernoid** [BeryJu/gravity#1093]
New Setup, building with 3 nodes.

First node is running, only changes made is to the admin password. Everything else is default.

When adding a second node, the logs of the second instance read:

`{"level":"info","ts":1719984521.414721,"logger":"instance","msg":"Gravity starting","instance":"grav2","version":"0.9.0-af608cc1","instance":"grav2","version":"0.9.0-af608cc1"}`

Relevant compose files:

Node#1

```
services:
  grav1:
    hostname: grav1
    image: ghcr.io/beryju/gravity:stable
    restart: unless-stopped
    container_name: grav1
    network_mode: host
    volumes:
      - /docker/gravity/data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
``` 

Node#2

```
services:
  grav2:
    hostname: grav2
    image: ghcr.io/beryju/gravity:stable
    restart: unless-stopped
    container_name: grav2
    network_mode: host
    environment:
      ETCD_JOIN_CLUSTER: bYD1XnvxqQCQJj0XImNlOeJsjE9Z+XTfN/OsH0nv8++XhUaYXOgsc5c3QjVam0no74Cg4p69hW/Ho1TbT9SGjA,http://10.15.0.20:8008
      BOOTSTRAP_ROLES: dns
    volumes:
      - /docker/gravity/data:/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
```
