### ISSUE TITLE
Unable to create a DNS zone with the UI

### ISSUE THREAD

**Issue by Haibread** [BeryJu/gravity#1258]
## Issue

When I try to create a DNS zone in the UI, I am facing an `error 400 Bad Request`.

Here is the request payload :

```
{
  "authoritative": false,
  "defaultTTL": 86400,
  "handlerConfigs": [
    {
      "type": "memory"
    },
    {
      "type": "etcd"
    }
  ]
}
```

And the response :

```
{
  "status": "INVALID_ARGUMENT",
  "error": "invalid argument: validation failed",
  "context": {
    "body": [
      "#: missing properties: \"hook\""
    ]
  }
}
```

Not sure if I am doing something wrong, I tried with multiple values/zone types

## Details on environment

Gravity is deployed with docker compose with the configuration :

```
services:
  gravity:
    hostname: dns01
    image: ghcr.io/beryju/gravity:stable
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/data
    environment:
      LOG_LEVEL: info
      BOOTSTRAP_ROLES: "dns;api;etcd;discovery;backup;monitoring;tsdb;tftp"
    # The default log level of info logs DHCP and DNS queries, so ensure
    # the logs aren't filling up the disk
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
    driver: local
```

Please let me know if you need anything else
