### ISSUE TITLE
Better blocklist management

### ISSUE THREAD

**Issue by gjsmo** [BeryJu/gravity#598]
The DNS blocking support is currently very rudimentary. As far as I can tell there is no (easy) way to:

* Add individual domains to a custom blacklist
* Whitelist domains
* Determine which list is blocking a particular request

It's also rather difficult to manage lists, all being in a single line in the configuration. My suggestion would be to rework the configuration as such:

* Blocklists are an array rather than a single line separated by semicolons
* Two more arrays, perhaps `domains_allowed` and `domains_blocked`, are available for adding individual domains

It appears blocky already supports this, so it should (mostly) be a matter of just passing these parameters on appropriately.

**Comment by BeryJu** [comment]
Explicit allow list support was added with https://github.com/BeryJu/gravity/pull/1272, also the configuration is no longer a single semicolon separated-string, it's now this format:

```yaml
- type: etcd
- allowlists:
    - s.youtube.com
  cache_ttl: 3600
  to:
    - 8.8.8.8:53
  type: forward_blocky
- to:
    - 8.8.8.8:53
  type: forward_ip
```
