### ISSUE TITLE
DHCP not working on Windows

### ISSUE THREAD

**Issue by obzocker** [BeryJu/gravity#776]
The DHCP on Windows does not work for me.

Every other device get's a valid lease. But all three of my Windows devices do not.

I have tried everything:
- new network driver install
- restart network adapter
- troubleshoot helper
- restart pc
- try commands : "netsh winsock reset" and "netsh int ip reset"

I also tried manually acquirering a new ip address with "ipconfig /release" and "ipconfig /renew" over the windows command line

but everytime I tried that I got the error (unfortunatly not usefull): "An error occurred while renewing interface Ethernet : The data is invalid."

I have installed gravity with docker-compose:

```
version: "3.8"

services:
  gravity:
    container_name: gravity
    hostname: gravity
    image: ghcr.io/beryju/gravity:stable
    restart: unless-stopped
    volumes:
      - gravity:/data
    network_mode: host

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  gravity:
    external: true
```

Is this problem known and are there workarounds?
