### ISSUE TITLE
Running Docker from inside LXC - WubUI timeouts

### ISSUE THREAD

**Issue by HilkopterBob** [BeryJu/gravity#899]
hey, i want to run Gravity as docker-ct from inside an lxc-ct and gravity constantly time-outs.

### Background:
I use proxmox and there isnt a great way to list docker-ct's inside the web-ui so i create an lxc for every docker-container. Normaly this works without problems, even for bigger software like nextcloud or your other software like authentik.

### The Problem:

If i start the container and goto ip:8008 i get :
![image](https://github.com/BeryJu/gravity/assets/117028104/3a68cd81-680b-411f-9071-d4b8e480e9d1)

### Docker Compose:
```yml
---
version: "3.4"

services:
  gravity:
    # Important for this to be static and unique
    hostname: gravity1
    image: ghcr.io/beryju/gravity:stable
    restart: unless-stopped
    network_mode: host
    volumes:
      - data:/data
    environment:
      LOG_LEVEL: info
    # The default log level of info logs DHCP and DNS queries, so ensure
    # the logs aren't filling up the disk
      INSTANCE_IP: 10.93.80.32
      BOOTSTRAP_ROLES: dns;dhcp;api;etcd;discovery;backup;monitoring;tsdb
      INSTANCE_IDENTIFIER: gravity1

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
    driver: local

```

### Docker Compose logs:
```logs
[root@gravity-1 gravity]# docker compose logs
gravity-1  | {"level":"info","ts":1707300248.659429,"logger":"instance","msg":"Gravity starting","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","version":"0.8.1-431a3b14"}
gravity-1  | {"level":"info","ts":1707300248.6597772,"logger":"instance","msg":"'etcd' in bootstrap roles, starting embedded etcd","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1"}
gravity-1  | {"level":"info","ts":1707300248.6599598,"logger":"role.etcd","msg":"starting embedded etcd","instance":"gravity1","version":"0.8.1-431a3b14"}
gravity-1  | {"level":"warn","ts":1707300248.659974,"logger":"role.etcd","msg":"Running http and grpc server on single port. This is not recommended for production.","instance":"gravity1","version":"0.8.1-431a3b14"}
gravity-1  | {"level":"warn","ts":1707300248.6861465,"logger":"role.etcd","msg":"simple token is not cryptographically signed","instance":"gravity1","version":"0.8.1-431a3b14"}
gravity-1  | {"level":"info","ts":1707300249.8925915,"logger":"role.etcd","msg":"embedded etcd Ready!","instance":"gravity1","version":"0.8.1-431a3b14","runtime":1232}
gravity-1  | {"level":"info","ts":1707300249.9010768,"logger":"instance","msg":"defaulting to bootstrap roles","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roles":["dns","dhcp","api","etcd","discovery","backup","monitoring","tsdb"]}
gravity-1  | {"level":"info","ts":1707300250.077662,"logger":"role.dhcp","msg":"loaded OUI database","instance":"gravity1","version":"0.8.1-431a3b14","size":2314848}
gravity-1  | {"level":"info","ts":1707300250.080591,"logger":"instance","msg":"role not configured","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roleId":"backup"}
gravity-1  | {"level":"info","ts":1707300250.0807662,"logger":"instance","msg":"started role","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roleId":"backup"}
gravity-1  | {"level":"info","ts":1707300250.0808737,"logger":"role.monitoring","msg":"starting monitoring Server","instance":"gravity1","version":"0.8.1-431a3b14","listen":"10.93.80.32:8009"}
gravity-1  | {"level":"info","ts":1707300250.0808954,"logger":"instance","msg":"started role","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roleId":"monitoring"}
gravity-1  | {"level":"info","ts":1707300250.0810893,"logger":"instance","msg":"started role","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roleId":"discovery"}
gravity-1  | {"level":"info","ts":1707300250.081661,"logger":"instance","msg":"started role","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roleId":"tsdb"}
gravity-1  | {"level":"info","ts":1707300250.0928617,"logger":"instance","msg":"started role","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roleId":"dns"}
gravity-1  | {"level":"info","ts":1707300250.0930395,"logger":"role.dns","msg":"starting DNS Server","instance":"gravity1","version":"0.8.1-431a3b14","listen":"10.93.80.32:53","proto":"tcp"}
gravity-1  | {"level":"info","ts":1707300250.0934095,"logger":"role.dns","msg":"starting DNS Server","instance":"gravity1","version":"0.8.1-431a3b14","listen":"10.93.80.32:53","proto":"udp"}
gravity-1  | {"level":"info","ts":1707300250.1085315,"logger":"instance","msg":"started role","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roleId":"dhcp"}
gravity-1  | {"level":"info","ts":1707300250.1087806,"logger":"role.dhcp","msg":"starting DHCP Server","instance":"gravity1","version":"0.8.1-431a3b14","port":67,"interface":"eth0"}
gravity-1  | {"level":"info","ts":1707300250.158462,"logger":"instance","msg":"started role","instance":"gravity1","version":"0.8.1-431a3b14","instance":"gravity1","roleId":"api"}
gravity-1  | {"level":"info","ts":1707300250.1586022,"logger":"role.api","msg":"starting API Server","instance":"gravity1","version":"0.8.1-431a3b14","listen":"10.93.80.32:8008"}
gravity-1  | {"level":"info","ts":1707300250.159003,"logger":"role.api","msg":"starting API Server (socket)","instance":"gravity1","version":"0.8.1-431a3b14","listen":"/var/run/gravity.sock"}
```
