### ISSUE TITLE
Can't create DNS zone(s)

### ISSUE THREAD

**Issue by nofuturekid** [BeryJu/gravity#922]
Please forgive my ignorance but I fired up Gravity with with `docker compose up` and this `docker-compose.yaml` on a Raspberry Pi 4 with Bookworm

docker-compose.yaml
```
version: '3.4'

services:
  gravity:
    # Important for this to be static and unique
    hostname: gravity1
    image: ghcr.io/beryju/gravity:stable
    restart: unless-stopped
    network_mode: host
    user: root
    volumes:
      - ./data:/data
    # The default log level of info logs DHCP and DNS queries, so ensure
    # the logs aren't filling up the disk
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
```

I can log into Gravity and successfully create DHCP scopes and also users but nothing else.
The gray "Next" button just won't turn blue, same happens for "Join a node"

![image](https://github.com/BeryJu/gravity/assets/7026230/e863fe03-a913-4297-86ff-2df1f05332aa)

![image](https://github.com/BeryJu/gravity/assets/7026230/c523549e-3097-4455-82cd-69354954e5c7)
